name: page_authentification
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  device_preview_plus: ^2.2.6
  cloud_firestore: ^5.6.6
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  provider: ^6.1.5
  geolocator: ^9.0.1 # Pour la géolocalisation
  url_launcher: ^6.0.10 # Pour ouvrir l'application de carte

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/foodifly.png
 
 
