// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG7vIhNT5BqDc7UkmXMzLmE3GFk3sZILo',
    appId: '1:640628382681:web:7d8599ac776f68fb1297c8',
    messagingSenderId: '640628382681',
    projectId: 'foodifly-a8c06',
    authDomain: 'foodifly-a8c06.firebaseapp.com',
    storageBucket: 'foodifly-a8c06.firebasestorage.app',
    measurementId: 'G-H1L10JZ503',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMakx63djIwHV0WiQk8mcYFdUkDLrJsfk',
    appId: '1:640628382681:android:2193f51c2801d7db1297c8',
    messagingSenderId: '640628382681',
    projectId: 'foodifly-a8c06',
    storageBucket: 'foodifly-a8c06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtdB07PZm21CuJdzIh5Kujafug3w9-RGg',
    appId: '1:640628382681:ios:e2c86ff02d66517a1297c8',
    messagingSenderId: '640628382681',
    projectId: 'foodifly-a8c06',
    storageBucket: 'foodifly-a8c06.firebasestorage.app',
    iosBundleId: 'com.example.pageAuthentification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtdB07PZm21CuJdzIh5Kujafug3w9-RGg',
    appId: '1:640628382681:ios:e2c86ff02d66517a1297c8',
    messagingSenderId: '640628382681',
    projectId: 'foodifly-a8c06',
    storageBucket: 'foodifly-a8c06.firebasestorage.app',
    iosBundleId: 'com.example.pageAuthentification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG7vIhNT5BqDc7UkmXMzLmE3GFk3sZILo',
    appId: '1:640628382681:web:9edff3c659940de11297c8',
    messagingSenderId: '640628382681',
    projectId: 'foodifly-a8c06',
    authDomain: 'foodifly-a8c06.firebaseapp.com',
    storageBucket: 'foodifly-a8c06.firebasestorage.app',
    measurementId: 'G-ZVN8L6BV8L',
  );
}
