import 'package:cloud_firestore/cloud_firestore.dart';

final FirebaseFirestore _firestore = FirebaseFirestore.instance;

final List<Map<String, dynamic>> foodTrucks = [
  {
    'nom': 'Tacofino',
    'email': 'contact@tacofino.com',
    'password': 'tacofino123',
    'telephone': '604-123-4567',
    'description': 'Cuisine mexicaine fusion servie depuis un camion légendaire à Vancouver.',
    'localisation': 'Vancouver, BC',
    'heureOuverture': '11:00',
    'heureFermeture': '20:00',
    'dateCreation': FieldValue.serverTimestamp(),
    'imageUrl': 'https://www.tacofino.com/wp-content/uploads/2021/01/food-truck.jpg',
  },
  {
    'nom': 'Randy\'s Roti and Doubles',
    'email': 'info@randysroti.com',
    'password': 'randys456',
    'telephone': '647-350-1400',
    'description': 'Spécialiste de la cuisine caribéenne avec roti et doubles authentiques.',
    'localisation': 'Toronto, ON',
    'heureOuverture': '10:00',
    'heureFermeture': '18:00',
    'dateCreation': FieldValue.serverTimestamp(),
    'imageUrl': 'https://www.blogto.com/upload/2015/04/20150406-randys.jpg',
  },
  {
    'nom': 'The Grilled Cheese',
    'email': 'hello@grilledcheese.ca',
    'password': 'grilled789',
    'telephone': '416-555-1234',
    'description': 'Des sandwichs au fromage grillé gourmets et créatifs.',
    'localisation': 'Toronto, ON',
    'heureOuverture': '12:00',
    'heureFermeture': '22:00',
    'dateCreation': FieldValue.serverTimestamp(),
    'imageUrl': 'https://media.blogto.com/articles/7f326_grilledcheese.jpg',
  },
  {
    'nom': 'The Happy Camper',
    'email': 'info@happycamper.com',
    'password': 'camper123',
    'telephone': '403-789-5678',
    'description': 'Pizzas artisanales cuites au feu de bois.',
    'localisation': 'Calgary, AB',
    'heureOuverture': '15:00',
    'heureFermeture': '23:00',
    'dateCreation': FieldValue.serverTimestamp(),
    'imageUrl': 'https://images.squarespace-cdn.com/content/v1/5b8f0/image.jpg',
  },
  {
    'nom': 'Buster\'s Sea Cove',
    'email': 'contact@busters.ca',
    'password': 'seafood123',
    'telephone': '416-555-5678',
    'description': 'Fruits de mer frais servis dans tout Toronto.',
    'localisation': 'Toronto, ON',
    'heureOuverture': '11:30',
    'heureFermeture': '21:00',
    'dateCreation': FieldValue.serverTimestamp(),
    'imageUrl': 'https://bustersseacove.ca/img/truck.jpg',
  },
  {
    'nom': 'The Mighty Cob',
    'email': 'info@mightycob.ca',
    'password': 'corny456',
    'telephone': '905-555-6789',
    'description': 'Maïs grillé avec des garnitures incroyables.',
    'localisation': 'Mississauga, ON',
    'heureOuverture': '12:00',
    'heureFermeture': '19:00',
    'dateCreation': FieldValue.serverTimestamp(),
    'imageUrl': 'https://s3.amazonaws.com/images.foodtruck.com/cob.jpg',
  },
  {
    'nom': 'Urban Smoke',
    'email': 'contact@urbansmoke.ca',
    'password': 'bbqurban123',
    'telephone': '905-555-7890',
    'description': 'Barbecue texan et viandes fumées tendres à souhait.',
    'localisation': 'Hamilton, ON',
    'heureOuverture': '11:00',
    'heureFermeture': '20:00',
    'dateCreation': FieldValue.serverTimestamp(),
    'imageUrl': 'https://www.urbansmoke.com/img/truck.jpg',
  },
  {
    'nom': 'The Churro Stop',
    'email': 'info@churrostop.ca',
    'password': 'sweetchurro',
    'telephone': '204-555-8901',
    'description': 'Churros croustillants et sauces sucrées maison.',
    'localisation': 'Winnipeg, MB',
    'heureOuverture': '14:00',
    'heureFermeture': '22:00',
    'dateCreation': FieldValue.serverTimestamp(),
    'imageUrl': 'https://churrostop.ca/assets/truck.jpg',
  },
  {
    'nom': 'The Frying Dutchmen',
    'email': 'info@dutchmen.ca',
    'password': 'fryfry2024',
    'telephone': '416-555-9012',
    'description': 'Frites hollandaises avec sauces variées.',
    'localisation': 'Toronto, ON',
    'heureOuverture': '11:00',
    'heureFermeture': '21:00',
    'dateCreation': FieldValue.serverTimestamp(),
    'imageUrl': 'https://fryingdutchmen.com/photos/truck.jpg',
  },
  {
    'nom': 'The Rolling Pin',
    'email': 'hello@rollingpin.ca',
    'password': 'rolling888',
    'telephone': '416-123-4567',
    'description': 'Beignets et pâtisseries créatives faites à la main.',
    'localisation': 'Toronto, ON',
    'heureOuverture': '08:00',
    'heureFermeture': '17:00',
    'dateCreation': FieldValue.serverTimestamp(),
    'imageUrl': 'https://rollingpin.ca/img/truck.jpg',
  },
  {
    'nom': 'The Meatball Shoppe',
    'email': 'info@themeatballshoppe.ca',
    'password': 'meatball123',
    'telephone': '416-555-2345',
    'description': 'Boulettes de viande artisanales, sauces maison.',
    'localisation': 'Toronto, ON',
    'heureOuverture': '11:00',
    'heureFermeture': '20:00',
    'dateCreation': FieldValue.serverTimestamp(),
    'imageUrl': 'https://www.pinterest.com/pin/52565520631460408/',
  },
  {
    'nom': 'The Poutine Machine',
    'email': 'contact@poutinemachine.ca',
    'password': 'poutine123',
    'telephone': '514-555-3456',
    'description': 'Poutines variées et garnies.',
    'localisation': 'Montréal, QC',
    'heureOuverture': '12:00',
    'heureFermeture': '23:00',
    'dateCreation': FieldValue.serverTimestamp(),
    'imageUrl': 'https://www.bestfoodtrucks.com/truck/the-poutine-machine/menu',
  },
  {
    'nom': 'Zilford\'s Fried Chicken',
    'email': 'info@zilfordsfriedchicken.ca',
    'password': 'friedchicken123',
    'telephone': '403-555-4567',
    'description': 'Poulet frit à la sudiste.',
    'localisation': 'Calgary, AB',
    'heureOuverture': '11:00',
    'heureFermeture': '21:00',
    'dateCreation': FieldValue.serverTimestamp(),
    'imageUrl': 'https://ellegourmet.ca/canadian-food-trucks/',
  },
  {
    'nom': 'Crack On',
    'email': 'contact@crackon.ca',
    'password': 'crackon2024',
    'telephone': '604-555-6789',
    'description': 'Œufs brouillés et sandwichs gourmets.',
    'localisation': 'Vancouver, BC',
    'heureOuverture': '07:00',
    'heureFermeture': '16:00',
    'dateCreation': FieldValue.serverTimestamp(),
    'imageUrl': 'https://www.crackon.ca/img/truck.jpg',
  },
  {
    'nom': 'Lime Truck',
    'email': 'contact@limetruck.com',
    'password': 'lime123',
    'telephone': '514-555-9876',
    'description': 'Cuisine californienne avec des tacos créatifs et des plats sains.',
    'localisation': 'Montréal, QC',
    'heureOuverture': '10:00',
    'heureFermeture': '22:00',
    'dateCreation': FieldValue.serverTimestamp(),
    'imageUrl': 'https://www.limetruck.com/img/truck.jpg',
  },
  {
    'nom': 'La Paloma',
    'email': 'info@lapaloma.ca',
    'password': 'paloma789',
    'telephone': '416-555-5678',
    'description': 'Cuisine mexicaine authentique avec tacos, burritos et quesadillas.',
    'localisation': 'Toronto, ON',
    'heureOuverture': '12:00',
    'heureFermeture': '23:00',
    'dateCreation': FieldValue.serverTimestamp(),
    'imageUrl': 'https://lapaloma.ca/images/truck.jpg',
  },
  {
    'nom': 'Butter Tart Truck',
    'email': 'info@buttertart.ca',
    'password': 'butter123',
    'telephone': '519-555-2345',
    'description': 'La meilleure tarte au beurre de tout le pays, servie dans un camion.',
    'localisation': 'London, ON',
    'heureOuverture': '09:00',
    'heureFermeture': '18:00',
    'dateCreation': FieldValue.serverTimestamp(),
    'imageUrl': 'https://buttertart.ca/truck.jpg',
  },
  {
    'nom': 'Meatball Shoppe',
    'email': 'contact@meatballshoppe.com',
    'password': 'meatballs123',
    'telephone': '905-555-9876',
    'description': 'Spécialiste des boulettes de viande maison avec différentes garnitures.',
    'localisation': 'Mississauga, ON',
    'heureOuverture': '11:00',
    'heureFermeture': '21:00',
    'dateCreation': FieldValue.serverTimestamp(),
    'imageUrl': 'https://meatballshoppe.com/truck.jpg',
  }
];

Future<void> addFoodTrucks() async {
  try {
    // Iterate through the list and add each food truck to Firestore
    for (var foodTruck in foodTrucks) {
      await _firestore.collection('foodTrucks').add(foodTruck);
    }
    print('Food trucks added successfully');
  } catch (e) {
    print('Error adding food trucks: $e');
  }
}

void main() async {
  // Call the function to add food trucks
  await addFoodTrucks();
}
